import type { Metadata } from "next";
import { Aclonica } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "../store/provider";

const inter = Aclonica({ weight: ["400"], subsets: [] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
